samples_demo:
    resource: "@SamplesDemoBundle/Controller/"
    type:     annotation
    prefix:   /samples

rest_demo:
    resource: "@RestDemoBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    type:     rest
    resource: Rest\DemoBundle\Controller\UsersController

products:
    type:     rest
    resource: Rest\DemoBundle\Controller\ProductsController