samples_demo:
    resource: "@SamplesDemoBundle/Controller/"
    type:     annotation
    prefix:   /

rest_demo:
    resource: "@RestDemoBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    type:     rest
    resource: Rest\DemoBundle\Controller\UsersController

hello_world:
    resource: "@RestDemoBundle/Resources/config/routing.yml"
    prefix:   /hello